version: '3'
services: 
  db:
    container_name: chatspace_db
    image: mysql:5.7
    environment: 
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: chatspace
    ports: 
      - "4306:3306"
    volumes: 
      - ./db/mysql_data:/var/lib/mysql
      
  
  web:
    container_name: chatspace_web
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes: 
      - .:/app_name
    ports: 
      - "3000:3000"
    links: 
      - db